import React,{useState} from 'react';
import data from './menu.json';
import macros from './macros.json';
import diet from './diet.json';
import ids from './mess-ids.json';
import './admin.css';
type Item={id:string;outlet:string;category:string;name:string;price:number|null;active:boolean;diet:string;kcal:number|null;protein_g:number|null;carbs_g:number|null;fat_g:number|null;macro_portion:string;macro_source:string};
type Hours={name:string;open:string;close:string;note:string};
const DAY=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
const MEAL=['Breakfast','Lunch','Snacks','Dinner'];
const OUTLETS=[...data.outlets.map(o=>o.name),'ANC','CNC','DNC','Mess'];
const initial:Item[]=data.outlets.flatMap((o,oi)=>o.cats.flatMap((c,ci)=>c.items.map((i,ii)=>{const id=`o${oi}-c${ci}-i${ii}`,m=(macros.base as Record<string,[number,number,number,number,string,string]>)[(macros.items as Record<string,string>)[id]];return {id,outlet:o.name,category:c.name,name:i.name,price:i.price==null?null:Number(i.price),active:true,diet:(diet as Record<string,string>)[id]||'unknown',kcal:m?.[0]??null,protein_g:m?.[1]??null,carbs_g:m?.[2]??null,fat_g:m?.[3]??null,macro_portion:m?.[4]||'',macro_source:m?'https://www.healthifyme.com/web/nutrifacts/'+m[5]:''}}))).concat(Object.entries(ids).map(([name,id])=>({id,outlet:'Mess',category:'Rotation',name,price:null,active:true,diet:'unknown',kcal:null,protein_g:null,carbs_g:null,fat_g:null,macro_portion:'',macro_source:''})));
const originalHours:Hours[]=[['Breakfast','07:30','09:30'],['Lunch','12:00','14:30'],['Snacks','17:00','18:00'],['Dinner','19:30','21:30'],...OUTLETS.slice(0,-1).map(x=>[x,'','','Hours not verified'])].map(x=>({name:x[0],open:x[1],close:x[2],note:x[3]||'Mess'}));
type Slot={id:string;meal:string;weekday:string;role:string;display_name:string};
const originalSlots:Slot[]=MEAL.flatMap(meal=>data.mess[meal as keyof typeof data.mess].flatMap((e,i)=>DAY.map(day=>({id:`${meal}-${i}-${day}`,meal,weekday:day,role:e.role,display_name:String(e[day as keyof typeof e]||'')}))));
export function AdminPanel({back}:{back:()=>void}){
 const [items,setItems]=useState<Item[]>(()=>{try{return JSON.parse(localStorage.getItem('bpgc-admin-demo-items')||'null')||initial}catch{return initial}});
 const [hours,setHours]=useState<Hours[]>(()=>{try{return JSON.parse(localStorage.getItem('bpgc-admin-demo-hours')||'null')||originalHours}catch{return originalHours}});
 const [slots,setSlots]=useState<Slot[]>(()=>{try{return JSON.parse(localStorage.getItem('bpgc-admin-demo-slots')||'null')||originalSlots}catch{return originalSlots}});
 const [view,setView]=useState('Overview'),[outlet,setOutlet]=useState('Gajalaxmi'),[q,setQ]=useState(''),[editing,setEditing]=useState<Item|null>(null),[newItem,setNewItem]=useState(false),[msg,setMsg]=useState(''),[day,setDay]=useState('Mon'),[meal,setMeal]=useState('Breakfast');
 const saveItems=(v:Item[])=>{setItems(v);try{localStorage.setItem('bpgc-admin-demo-items',JSON.stringify(v))}catch{}};
 const saveHours=(v:Hours[])=>{setHours(v);try{localStorage.setItem('bpgc-admin-demo-hours',JSON.stringify(v))}catch{}};
 const saveSlots=(v:Slot[])=>{setSlots(v);try{localStorage.setItem('bpgc-admin-demo-slots',JSON.stringify(v))}catch{}};
 const choices=['Overview','Items','Hours','Mess rotation','Roles','Activity'];
 const draft=(item?:Item)=>{setEditing(item||{id:'demo-'+crypto.randomUUID(),outlet,category:'',name:'',price:null,active:true,diet:'unknown',kcal:null,protein_g:null,carbs_g:null,fat_g:null,macro_portion:'',macro_source:''});setNewItem(!item);setMsg('')};
 const change=(key:keyof Item,value:string|number|boolean|null)=>setEditing(x=>x?{...x,[key]:value}:x);
 const commit=()=>{if(!editing)return;let x=editing;if(!x.name.trim()||!x.category.trim()||x.outlet!=='Mess'&&(x.price==null||x.price<0)){setMsg('Enter a name, category and price.');return}let v=[x.kcal,x.protein_g,x.carbs_g,x.fat_g];if(v.some(n=>n!==null)&&(v.some(n=>n===null||n<0)||!x.macro_portion||!x.macro_source)){setMsg('Complete all four macro fields, portion and source together.');return}saveItems([...items.filter(i=>i.id!==x.id),x]);setEditing(null);setMsg('Saved in this browser only. The public menu is unchanged.')};
 return <div className="admin-app"><div className="admin-head"><div><strong>BPGC / food</strong><span>Admin preview</span></div><button onClick={back}>← Public menu</button></div><div className="admin-warning" role="status"><strong>Preview only · no database connected</strong> Edits stay in this browser and do not change the public menu. Usage figures are unavailable, not zero. No one has admin access yet.</div><nav className="admin-tabs" aria-label="Admin sections">{choices.map(x=><button className={view===x?'active':''} key={x} onClick={()=>{setView(x);setMsg('')}}>{x}</button>)}</nav><p role="status" className="admin-msg">{msg}</p>
 {view==='Overview'&&<><h2>Usage dashboard</h2><p>App opens and menu selections are not physical visits. These figures need a connected backend.</p><div className="admin-grid">{['Unique browser IDs','App opens','Mess menu views',...OUTLETS.slice(0,-1).map(x=>x+' menu views')].map(x=><div className="admin-card" key={x}><small>{x}</small><strong>—</strong><small>Not tracking in preview</small></div>)}</div></>}
 {view==='Items'&&<><div className="admin-row"><h2>Food items</h2><button onClick={()=>draft()}>+ Add item</button></div><p>Manage names, prices, diet tags and sourced macros. Add NC items under ANC, CNC or DNC when the menus arrive. Archive keeps past likes and edit history when connected.</p><div className="admin-row"><select aria-label="Choose outlet" value={outlet} onChange={e=>setOutlet(e.target.value)}>{OUTLETS.map(x=><option key={x}>{x}</option>)}</select><input aria-label="Search items" placeholder="Search items" value={q} onChange={e=>setQ(e.target.value)}/></div><div className="admin-list">{items.filter(x=>x.outlet===outlet&&`${x.name} ${x.category}`.toLowerCase().includes(q.toLowerCase())).slice(0,120).map(x=><div key={x.id}><span><strong>{x.name}</strong> {x.active?'':'[Archived]'}<small>{x.category} · {x.price===null?'Price unavailable':'₹'+x.price}{x.kcal===null?'':' · ≈'+x.kcal+' kcal'}</small></span><button onClick={()=>draft(x)}>Edit</button></div>)}</div></>}
 {view==='Hours'&&<><h2>Hours and service windows</h2><p>Outlet hours have not been verified. Blank means unknown.</p><div className="admin-grid">{hours.map(h=><div className="admin-card admin-hour" key={h.name}><strong>{h.name}</strong><label>Opens<input type="time" value={h.open} onChange={e=>saveHours(hours.map(x=>x.name===h.name?{...x,open:e.target.value}:x))}/></label><label>Closes<input type="time" value={h.close} onChange={e=>saveHours(hours.map(x=>x.name===h.name?{...x,close:e.target.value}:x))}/></label><label>Note<input value={h.note} onChange={e=>saveHours(hours.map(x=>x.name===h.name?{...x,note:e.target.value}:x))}/></label></div>)}</div><p>Every change here is saved only in this browser's preview.</p></>}
 {view==='Mess rotation'&&<><h2>Mess rotation</h2><p>Choose a day and meal, then edit the dish shown in each slot.</p><div className="admin-row"><select value={day} onChange={e=>setDay(e.target.value)}>{DAY.map(x=><option key={x}>{x}</option>)}</select><select value={meal} onChange={e=>setMeal(e.target.value)}>{MEAL.map(x=><option key={x}>{x}</option>)}</select></div><div className="admin-list">{slots.filter(s=>s.meal===meal&&s.weekday===day).map(s=><label key={s.id}>{s.role}<input value={s.display_name} onChange={e=>saveSlots(slots.map(x=>x.id===s.id?{...x,display_name:e.target.value}:x))}/></label>)}</div></>}
 {view==='Roles'&&<><h2>Admin roles</h2><p>Only <strong>f20230965@goa.bits-pilani.ac.in</strong> may approve or revoke admin and super admin roles after a verified sign-in. There is no campus-email restriction. The founding account must be bootstrapped in Supabase first.</p><button disabled>Approve admin</button><button disabled>Approve super admin</button><p>No role changes are possible in this preview.</p></>}
 {view==='Activity'&&<><h2>Change history</h2><p>Database-connected edits will have a server-side audit trail. Local preview changes are not an audit log.</p></>}
 {editing&&<div className="admin-modal" role="dialog" aria-modal="true" aria-label="Edit menu item"><div className="admin-editor"><h2>{newItem?'Add item':'Edit item'}</h2><p>{newItem?'A stable ID is generated on save.':'ID: '+editing.id}</p><div className="admin-form"><label>Outlet<select value={editing.outlet} onChange={e=>change('outlet',e.target.value)}>{OUTLETS.map(x=><option key={x}>{x}</option>)}</select></label><label>Category<input value={editing.category} onChange={e=>change('category',e.target.value)}/></label><label>Name<input value={editing.name} onChange={e=>change('name',e.target.value)}/></label><label>Price ₹<input type="number" min="0" step="0.01" value={editing.price??''} onChange={e=>change('price',e.target.value===''?null:Number(e.target.value))}/></label><label>Diet<select value={editing.diet} onChange={e=>change('diet',e.target.value)}>{['unknown','veg','egg','nonveg'].map(x=><option key={x}>{x}</option>)}</select></label><label>Visible<input type="checkbox" checked={editing.active} onChange={e=>change('active',e.target.checked)}/></label>{(['kcal','protein_g','carbs_g','fat_g'] as const).map(k=><label key={k}>{k}<input type="number" min="0" step="0.1" value={editing[k]??''} onChange={e=>change(k,e.target.value===''?null:Number(e.target.value))}/></label>)}<label>Portion<input value={editing.macro_portion} onChange={e=>change('macro_portion',e.target.value)}/></label><label>Source URL<input value={editing.macro_source} onChange={e=>change('macro_source',e.target.value)}/></label></div><p>{msg}</p><div className="admin-row"><button onClick={commit}>Save preview</button>{!newItem&&<button onClick={()=>change('active',false)}>Archive</button>}<button onClick={()=>setEditing(null)}>Cancel</button></div></div></div>}
 </div>
}
